name: flutter_file_downloader_example
description: Demonstrates how to use the flutter_file_downloader plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_file_downloader:
    # When depending on this package from a real application you should use:
    #   flutter_file_downloader: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true