name: flutter_file_downloader
description: A simple flutter plugin that downloads any file type to downloads directory
version: 1.1.0
homepage: https://github.com/abdallah-odeh/flutter_files_downloader

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  lints: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_file_downloader
        pluginClass: FlutterFileDownloaderPlugin