name: flutter_file_downloader
description: A simple flutter plugin that downloads any file type to downloads directory
version: 1.2.2-dev.1
issue_tracker: https://github.com/abdallah-odeh/flutter_files_downloader/issues
homepage: https://github.com/abdallah-odeh/flutter_files_downloader

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.2.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  lints: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.odehbros.flutter_file_downloader
        pluginClass: FlutterFileDownloaderPlugin
#      ios:
#        pluginClass: FlutterFilesDownloaderPlugin